DELETE http://localhost:3003/api/blogs/5ff8e462fff65dd931a9d2a1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im90aGVydXNlciIsImlkIjoiNWZmOGU3NTQwMmE5OTFlNzE5MjUxNDM5IiwiaWF0IjoxNjEwMTQ3NjkxfQ.WjLlcampivH78DSC96oNZ21dNN2oOJqXXdmKDo9Pb9k

###

DELETE http://localhost:3003/api/blogs/5ff8e462fff65dd931a9d2a1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im15dXNlciIsImlkIjoiNWZmOGMwZjJkNDkyMTRhODZhOWQzZTY0IiwiaWF0IjoxNjEwMTQ3ODk2fQ.a7x91w2Bl2zWsLB2gkzdwmbljoMroaJow5lEyV127Vo