POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im15dXNlciIsImlkIjoiNWZmOGMwZjJkNDkyMTRhODZhOWQzZTY0IiwiaWF0IjoxNjEwMTQ2OTA4fQ.A80Il7eYbDpzqMKEQk8Vf-zMfWFWDMOtwaqfb25GHkk

{
  "title": "Hello world3",
  "author": "Me",
  "url": "/blog2",
  "likes": 0
}